Text/LaTeX/Packages/AMSMath.hs

I added the most commonly used variable accents from AMSMath, like `\dot{ }` for derivatives or `\hat{ }` for estimates.
This is my first attempt at hacking on HaTeX, and I mostly did it by the cargo cult method, so any advice would be appreciated.

Added commonly used variable accent commands from AMSMath

---

Text/LaTeX/Packages/AMSMath.hs

As discussed in #51, this provides implementations for `signum`, `atanh`, `acosh`, and `asinh` from `Num` and `Floating` in terms of `operatorname`.

Operators for Num and Floating

---

Text/LaTeX/Packages/AMSMath.hs

The `\partial` symbol ∂ wasn't in the `AmsMath` module at all. Apart from adding it, I also put in a non-italic `d` (for total differentiation `dy/dx`, or integrals `∫ f(x) dx`). Also, I don't like how `integralFromTo` worked: `\int_a^b` just adds `a` and `b` as sub/superscripts, _right_ of the integration symbol. To make them appear _above and below_ the symbol, like with sums, we need to write `\int\limits_a^b`; I made that the default.

Some utility for primitive calculus operations

---

.gitignore

This is a very basic gitignore file. It makes git much easier to use from the command line alongside cabal sandboxes.

Added .gitignore file to simplify haskell development.

---

Text/LaTeX/Packages/Hyperref.hs

This patch adds helper functions for setting options of the Hyperref package. These are the commonly used ones related to PDF metadata. To be truly comprehensive there are dozens of others related to viewport setting and default print options, but these are the commonly used ones.

Added package options for the hyperref package related to PDF metadata.

---

HaTeX.cabal
Text/LaTeX/Packages/QRCode.hs

This is a wrapper for the `qrcode` LaTeX package which can be used to generate QR codes in documents.

Wrapper for the qrcode package

---

HaTeX.cabal

Since GHC8 comes with transformers-0.5.2.0
This compiles with GHC 8.0.1-rc4.

Increase upper bound of transformers

---

Text/LaTeX/Packages/AMSMath.hs

ec9a178 enforced braces around the `a` in `a_b`. This prevents the LaTeX error of double subscripts in expressions like `a_b_c`, but unfortunately it also prohibits the commonly used pattern `a_b^c` from getting rendered a `c` stacked over `b`. Also, it outright breaks integrals with limits.
To bring back this functionality without also enabling the LaTeX errors again, I introduced a _new_ operator `!^`, for stacked sub- and superscript.
Also, I patched `sumFromTo` etc. to apply their limits as `raw` sub- and superscripts.

Remediate stacking of sub- and superscripts.

---

Examples/mathSpaces.hs
Text/LaTeX/Packages/AMSMath.hs

I have got some suggestions for the missing math space commands on [TeX, LaTeX and Friends](http://chat.stackexchange.com/transcript/message/30723213#30723213) chat.

Implement missing math space commands

---

Text/LaTeX/Base/Writer.hs

This function is analogous to mapErrorT, mapExceptT, mapStateT, etc.

Add mapLaTeXT, a helper function for building trans monad instances

---

Text/LaTeX/Packages/QRCode.hs

```
qr CodeOptions{ includePadding = True
, link = False
, errorLevel = High} "Hello!"
```
currently generates the following Latex fragment:
```
\qrcode[padding,nolink,level=h]{Hello!}
```
which leads to the following logs at compile time:
```
<QR code requested for "Hello!
" in version 0-M.>
<Error-correction level increased from M to H at no cost.>
<Calculating QR code for "Hello!
" in version 1-H.>
```
Despite the `errorLevel = High`, Latex interprets the qrcode request as version `0-M`.
According to [qrcode documentation](http://ftp.math.purdue.edu/mirrors/ctan.org/macros/latex/contrib/qrcode/qrcode.pdf#3), the level has to be `L`, `M`, `Q` or `H`.
The issue was that the qrcode level generated by HaTeX was in lower case letter instead of a capital one.
With this patch, the above piece …

Fix case of qrcode level option

---

Text/LaTeX/Base/Syntax.hs

Fixes #89 
Also makes spacing in `deriving` clauses a little more consistent with other modules (compare `Types`).

Derive Data, Generic, and Typeable for LaTeX type

---

HaTeX.cabal
Text/LaTeX/Base/Syntax.hs

This is useful mainly in that it allows using TeX snippets as keys in
quick-lookup hash maps.
The `hashable` package is only a light dependency and the instances are completely
`Generic`-derived, so this seems sensible enough.

Hashable instances for the LaTeX syntax.

---

Examples/biblatex.hs
HaTeX.cabal
Text/LaTeX/Packages/BibLaTeX.hs

I thought about what commands apart from the inevitable `addbibresource` and `printbibliography` should be in the module, but could not decide how deep to go down that rabbit hole.
What I would really like to add is a monad transformer that allows conveniently citing stuff by just giving a DOI and having the Haskell programm automatically look up the bibliography information. This should be doable in the way [the DOI package](http://hackage.haskell.org/package/doi-0.0.2/docs/DOI.html) does it. (But I reckon such a feature shouldn't be included in the HaTeX package, since it involves networking etc.?)

Rudimentary binding to BibLaTeX package, and simple example.

---

HaTeX.cabal
Text/LaTeX/Base/Class.hs

This could be useful when defining fractions of whitespace.
For example: `4.0\baselineskip` won't compile but `[4.0\baselineskip]`
will.

added square braces

---

Text/LaTeX/Base/Commands.hs

According to the [LaTeX/Lengths](https://en.wikibooks.org/wiki/LaTeX/Lengths), the argument of `stretch` can be a floating point number:
> The command `\stretch{factor}` generates a special rubber space where `factor` is a number, possibly a **float**.

Fix the type of stretch

---

Examples/multirow.hs
Text/LaTeX/Packages/Multirow.hs

Just after submitting the PR that adds multirows, I think I have found a better type for the `multirow` function. Sorry for the inconvenience.
The width of a multirow cell can be a dimension or '*' (indicating
that the natural width of the text is to be used) or '=' (indicating
that the specified width of the column in which the multirow entry is
set should be used).
Because of those two special cases its type has initially been set as
'LaTeXC l => l'. But it can be 'Measure', which supports the special
cases as 'CustomMeasure' and better fits the purpose of the width
argument.

Use Measure for the width of a multirow cell

---

Text/LaTeX/Base/Warnings.hs

Now every monoid has a Semigroup instance, as required per
the SMP.
https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid
Fixes https://github.com/Daniel-Diaz/HaTeX/issues/113.

Also make `TeXCheck` a semigroup.

---

Text/LaTeX/Packages/AMSFonts.hs
Text/LaTeX/Packages/AMSMath.hs
Text/LaTeX/Packages/AMSSymb.hs

[This feature](https://haskell-haddock.readthedocs.io/en/latest/markup.html#mathematics-latex) makes the examples as realistic as they can be.

Make use of Haddock's MathJax integration for examples in the documentation.

---

Text/LaTeX/Base/Math.hs
Text/LaTeX/Packages/AMSSymb.hs

...actually, many of these don't even require AMSSymb, only vanilla LaTeX.
Not sure if those should go straight in `Base.Commands`?

Add all the arrow symbols in AMSSymb.

---

Examples/matrices.hs
Examples/multirow.hs
Text/LaTeX/Base/Commands.hs
Text/LaTeX/Base/Math.hs
Text/LaTeX/Base/Parser.hs
Text/LaTeX/Base/Pretty.hs
Text/LaTeX/Base/Syntax.hs
Text/LaTeX/Base/Writer.hs
Text/LaTeX/Packages/Graphicx.hs
Text/LaTeX/Packages/Hyperref.hs
Text/LaTeX/Packages/Multirow.hs
Text/LaTeX/Packages/QRCode.hs
Text/LaTeX/Packages/TikZ/PathBuilder.hs
Text/LaTeX/Packages/TikZ/Syntax.hs
Text/LaTeX/Packages/Trees.hs

After running `hlint` some suggestions showed up. The following suggestions have been ignored:
```
Examples/multirow.hs:28:5: Suggestion: Reduce duplication
Found:
mempty & "Column g2b" <> lnbk
mempty & "Column g2c" <> lnbk
mempty & "Column g2d" <> lnbk
hline
Why not:
Combine with Examples/multirow.hs:45:5
Text/LaTeX/Base/Class.hs:56:26: Suggestion: Use const
Found:
\ _ -> l
Why not:
const l
Text/LaTeX/Base/Commands.hs:1167:1: Suggestion: Use camelCase
Found:
hatex_version = ...
Why not:
hatexVersion = ...
3 hints
```
(the `const` was already merged into the `master`)

Hlint improvements

---

Examples/biblatexDOI.hs
HaTeX.cabal
Text/LaTeX/Packages/BibLaTeX.hs

We discussed this already here: https://github.com/Daniel-Diaz/HaTeX/pull/102
I've meant to think about a better way to do this, [maybe in another module or package](https://github.com/Daniel-Diaz/HaTeX/issues/121), but I can't seem to get around to actually doing it. Are there objections if I just merge this as it stands, in the `Packages/Biblatex` module?

Simple doi references

---

HaTeX.cabal

Fixes #152.
Tested using 'cabal test'.
The line has a carriage return since that was auto-detected by NeoVIM. If you want the the file with Unix newlines, I can change the whole file using dos2unix.

Allow bytestring version 0.11

---

HaTeX.cabal

Tested using
cabal test --constraint='text>=2' --constraint='hashable>=1.4'

Allow hashable 1.4.* and text 2.0.*
